---
- hosts: build-tools
  roles:
    - rfhayashi.rake
    - rfhayashi.vagrant
  tasks:
    - include: jdk.yml
    - name: installs which
      yum: name=which
    - name: Purge yum cache
      command: yum clean all
