---
- hosts: build-tools
  roles:
    - rfhayashi.rake
    - rfhayashi.vagrant
  tasks:
    - include: jdk.yml
    - name: installs epel
      yum: name=epel-release
    - name: installs ansible
      yum: name=ansible
    - name: installs which
      yum: name=which
    - name: installs ssh
      yum: name=openssh-clients
    - name: installs rsync
      yum: name=rsync
    - name: Purge yum cache
      command: yum clean all
