Vagrant.configure('2') do |config|
  require 'yaml'

  conf = YAML::load_file(ENV['AWS_CONFIG_FILE'])

  config.vm.box = 'dummy'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = conf['access_key_id']
    aws.secret_access_key = conf['secret_access_key']
    aws.keypair_name = conf['keypair_name']
    aws.instance_type = conf['instance_type'] || 't2.small'
    aws.subnet_id = conf['subnet_id']
    aws.security_groups = conf['security_groups']

    aws.ami = conf['ami'] || 'ami-b73b63a0'

    override.ssh.username = conf['username'] || 'ec2-user'
    override.ssh.private_key_path = conf['private_key_path'] || ENV['AWS_PRIVATE_KEY_FILE']
  end

  config.vm.provision 'ansible' do |a|
    a.sudo = true
    a.playbook = 'vagrant.yml'
    a.galaxy_role_file = 'requirements.yml'
    a.verbose = 'vv'
  end
end
